### ISSUE TITLE
Edit the menu

### ISSUE THREAD

**Issue by maniiacl** [GavickPro/Meet-Gavern#113]
Im struggling to edit the menu on meetgavern, I want to change colour and height but when I try to change it it changes also the whole page color I guess because its inside "container" and its connected to the whole page, I tried creating a new class=header and give a color but the height will not display the way I want...
Whats the easy way to change width height and add small edits without interference to other items?
Or where is the code to edit the height of the menu "header.container.fluid 1245px x 67px" ?

Thank you

**Comment by adifer** [comment]
Hello, I installed Meet-Gavern in my joomla and it looks very good, but I can not customize anything without a template.

I'm customizing on override.css and the only code that worked was removing the copyright.

every code that I put to change the background color, color of the top bar in the menu, not right, nothing changes.

how can I customize it, what can be happening?
