### ISSUE TITLE
CSS question (custom, override, media/jui order)

### ISSUE THREAD

**Issue by Ruud68** [GavickPro/Meet-Gavern#119]
Hi,
I using the templates custom css code field to change the look and feel of some parts of my website. I have finished testing and want to place the adjusted css code in the override.css. Now I am faced with an issue: this doesn't work for all changes. As it turns out, the override.css is overridden by the component's css file and by joomla's own bootstrap css files (e.g. /media/jui/css/bootstrap.min.css)

What I would expect is the following order (in order of loading):
1. joomla bootstrap css files (media/jui/css/)
2. Template (your) bootstrap css files
3. template.css
4. if present: component / modules css files
5. templates override.css file
6. template custom css code

the order now turns out to be:
1. Template (your) bootstrap css file
2. template.css
3. templates override.css file
4. joomla bootstrap css files
5. if present: component / modules css files
6. template custom css code

Am I missing something?
thanks,
Ruud.

**Comment by adifer** [comment]
Hello, I installed Meet-Gavern in my joomla and it looks very good, but I can not customize anything without a template.

I'm customizing on override.css and the only code that worked was removing the copyright.

every code that I put to change the background color, color of the top bar in the menu, not right, nothing changes.

how can I customize it, what can be happening?
