### ISSUE TITLE
Gk Extra Menu on mobile devices

### ISSUE THREAD

**Issue by luciffere** [GavickPro/Meet-Gavern#227]
Hello. I use gavern framework for my custom themes and i not want to use responsive settings.
In this case, the menu is shown and function ok on desktop, but in mobile devices if i put the finger on any first links from menu, the submenus not appear. Thank you for your response.

**Comment by dziudek** [comment]
Sorry but if you don't want to use the RWD layout then you have to apply custom changes will make the menu working - it is a custom work beyond of our technical support.
