### ISSUE TITLE
Mobile Menu doesn't work on Category blog pages

### ISSUE THREAD

**Issue by krachmann** [GavickPro/Meet-Gavern#231]
This is even visible on Gavick's demo site for the template. When you make the browser window narrow to check what it looks like on mobile devices, menu opens only once. then if you resize the window to a bigger size, menu disappears completely. Does not work on Android phone either. I found all the discussions about the problem and used all the fixes for gk.menu.js see https://github.com/GavickPro/Meet-Gavern/commit/9ad8b2163cfcbe3a2b35636fba012462280da548 but it doesn't work. Now I have found out that it actually DOES work on pages for which the menu item is set to only one content item, or "featured articles", but it does NOT work on category blog pages. So I think the problem is not a bug in the gk.menu.js BUT either in the file /html/com/content/category/blog.php or html/com_content/category/blog_item.php . Sorry I'm not good enough in PHP to contribute to the solution myself.

**Comment by allertec** [comment]
I`ve got the same problem :(

**Comment by dziudek** [comment]
This issue is caused by mootools - if you want to fix it, please open layouts/default.php file and add:

```php
GKParser::$customRules['/<script src="(.*?)media\/system\/js\/mootools-core.js" type="text\/javascript"><\/script>/mi'] = '';
GKParser::$customRules['/<script src="(.*?)media\/system\/js\/mootools-more.js" type="text\/javascript"><\/script>/mi'] = '';
```
