### ISSUE TITLE
Problem with template settings at the backend joomla 

### ISSUE THREAD

**Issue by said86** [GavickPro/Meet-Gavern#233]
Dir Sir or Madam,

I've got a problem with the ,,Meet Gravern Template" on my joomla Backend, on the template settings.

I'm using Joomla 3.4.1 and latest version from the meet-g. template.

1.) I've got a problem with the Button "Load" and "Delete" Both Buttons are not on their exact position and a little bit too high located. (screenshot 1.jpg)

2.) At all dropdown menu's, I cant see the list correctly. I can see only the first option. (screenshot 2.jpg)

Can you help me to fix it?
Many thanks in advance for your help.

Greetings
Said S.

![1](https://cloud.githubusercontent.com/assets/11939267/7132911/ea530692-e28d-11e4-93e1-3bea09f78ce8.jpg)
![2](https://cloud.githubusercontent.com/assets/11939267/7132912/ea58d252-e28d-11e4-8579-749b72694a60.jpg)

**Comment by Ruud68** [comment]
I can confirm: same issues as @said86 on multiple sites

**Comment by dziudek** [comment]
Fixed in the following commits: 
https://github.com/GavickPro/Meet-Gavern/commit/e192c8bd84ebdf326fa2d49c09c34438c6d79fb2
https://github.com/GavickPro/Meet-Gavern/commit/a5270a2cd6c26c9805d62dab9ee87d1f05517a64
