### ISSUE TITLE
seblod compnent for joomla is kind of blocked..

### ISSUE THREAD

**Issue by jaleotg** [GavickPro/Meet-Gavern#235]
I've got your university template on my web site. I'd like to build extended registration forms using seblod component, (this is a very powerful cck). However, When I create form-seblod type of menu position, the front end does not "follow" the settings in the back end. when I add a new field to to the user registration form(in the back-end), it doesn't appear in the front end. I have checked it on clean quickstart university template installation. What is strange (for me) that it also affects other-joomla native templates if the university one installed. Are you able to give me any tip on it? I tried to disable different parts of installation, but nothing helps.

**Comment by piotrkunicki** [comment]
Hello,
This repository is for free Meet Gavern template only. Regarding the University template, please create new thread on our support forum: https://www.gavick.com/forums/university
