### ISSUE TITLE
FullText image error

### ISSUE THREAD

**Issue by wonderdance** [GavickPro/Meet-Gavern#244]
Fatal error: Call to a member function get() on a non-object 
in /...../..../templates/meet_gavern/html/com_content/article/default.php on line 57

When article has full image $templateParams is undefined and 
$ogfb_image = $templateParams->get('ogfb_image','');  throws error.

I move 
     $templateParams = JFactory::getApplication()->getTemplate(true)->params;
to top.

Joomla 3.4

**Comment by dziudek** [comment]
Fixed: https://github.com/GavickPro/Meet-Gavern/commit/cabfe2aab991975a08ee64c02bab0a0d59d65e37

Thank you for your feedback.
