### ISSUE TITLE
Fatal Error: Cannot redeclare class lessc_formatter_compressed 

### ISSUE THREAD

**Issue by 810** [GavickPro/Meet-Gavern#59]
Fatal Error: Cannot redeclare class lessc_formatter_compressed in templates/meet_gavern/lib/framework/lessparser.php on line 2895

**Comment by xillibit** [comment]
@bkrztuk : do-you have changed something in the meet gavern code to avoid this king of issue ? Because it still exist with meet gavern 1.4.0 : http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/132784-server-error-500#163416

**Comment by dziudek** [comment]
I've merged fix from Ruud68.

**Comment by mahagr** [comment]
Nice, thanks!
